var searchData=
[
  ['desc',['desc',['../structmkldnn_1_1memory_1_1desc.html',1,'mkldnn::memory']]],
  ['desc',['desc',['../structmkldnn_1_1convolution__relu__forward_1_1desc.html',1,'mkldnn::convolution_relu_forward']]],
  ['desc',['desc',['../structmkldnn_1_1inner__product__forward_1_1desc.html',1,'mkldnn::inner_product_forward']]],
  ['desc',['desc',['../structmkldnn_1_1convolution__backward__weights_1_1desc.html',1,'mkldnn::convolution_backward_weights']]],
  ['desc',['desc',['../structmkldnn_1_1batch__normalization__backward_1_1desc.html',1,'mkldnn::batch_normalization_backward']]],
  ['desc',['desc',['../structmkldnn_1_1batch__normalization__forward_1_1desc.html',1,'mkldnn::batch_normalization_forward']]],
  ['desc',['desc',['../structmkldnn_1_1convolution__backward__data_1_1desc.html',1,'mkldnn::convolution_backward_data']]],
  ['desc',['desc',['../structmkldnn_1_1softmax__forward_1_1desc.html',1,'mkldnn::softmax_forward']]],
  ['desc',['desc',['../structmkldnn_1_1eltwise__backward_1_1desc.html',1,'mkldnn::eltwise_backward']]],
  ['desc',['desc',['../structmkldnn_1_1eltwise__forward_1_1desc.html',1,'mkldnn::eltwise_forward']]],
  ['desc',['desc',['../structmkldnn_1_1convolution__forward_1_1desc.html',1,'mkldnn::convolution_forward']]],
  ['desc',['desc',['../structmkldnn_1_1pooling__backward_1_1desc.html',1,'mkldnn::pooling_backward']]],
  ['desc',['desc',['../structmkldnn_1_1pooling__forward_1_1desc.html',1,'mkldnn::pooling_forward']]],
  ['desc',['desc',['../structmkldnn_1_1lrn__backward_1_1desc.html',1,'mkldnn::lrn_backward']]],
  ['desc',['desc',['../structmkldnn_1_1lrn__forward_1_1desc.html',1,'mkldnn::lrn_forward']]],
  ['desc',['desc',['../structmkldnn_1_1inner__product__backward__weights_1_1desc.html',1,'mkldnn::inner_product_backward_weights']]],
  ['desc',['desc',['../structmkldnn_1_1inner__product__backward__data_1_1desc.html',1,'mkldnn::inner_product_backward_data']]]
];
